@hostname = localhost
@port = 7261
@host = {{hostname}}:{{port}}
@contentType = application/json

### Get all running games

GET https://{{host}}/games/

### Create a new game

@gameid = a1275005-2fba-44ca-9002-83284c734850

POST https://{{host}}/games
Content-Type: {{contentType}}

{
  "gameType": 0,
  "playerName": "Testplayer"
}

### Get a specific game

GET https://{{host}}/games/{{gameid}}

### Set a move

POST https://{{host}}/games/{{gameid}}/moves
Content-Type: {{contentType}}

{
  "gameId": "{{gameid}}",
  "gameType": 0,
  "moveNumber": 1,
  "colorFields":  [
    { "color":"red" },
    { "color": "blue" },
    { "color": "green" },
    { "color": "yellow" }      
  ] 
}